source 'https://github.com/CocoaPods/Specs'
#source 'http://192.168.240.26/ios/BMSpecs'

platform :ios, "7.0"

inhibit_all_warnings!
target:BMNetworking do
    #pod "AFNetworking" #网络

    pod 'AFNetworking/Serialization', '3.2.1'
    pod 'AFNetworking/Security', '3.2.1'
    pod 'AFNetworking/Reachability', '3.2.1'
    pod 'AFNetworking/NSURLSession', '3.2.1'
end

#常用命令
#   pod install --verbose --no-repo-update
#   pod update --verbose --no-repo-update
