source 'https://github.com/CocoaPods/Specs.git'
# pod trunk push --allow-warnings
#pod repo remove trunk
platform :ios, "9.0"

inhibit_all_warnings!
target:BMNetworking do
    #pod "AFNetworking" #网络

    pod 'AFNetworking/Serialization', '4.0.1'
    pod 'AFNetworking/Security', '4.0.1'
    pod 'AFNetworking/Reachability', '4.0.1'
    pod 'AFNetworking/NSURLSession', '4.0.1'


end

#常用命令
#   pod install --verbose --no-repo-update
#   pod update --verbose --no-repo-update
